install.packages("dplyr")
library(dplyr)
my_data <- read.csv2("household_power_consumption.txt")
days <- filter(my_data, Date == "1/2/2007" | Date == "2/2/2007")
DateTime <- strptime(paste(days$Date, days$Time), "%d/%m/%Y %H:%M:%S")
png(file="plot3.png",width=480,height=480)
plot(DateTime,as.numeric(days$Sub_metering_1), type = "l", ylab= "Energy sub metering", xlab="", col="black")
lines(DateTime,as.numeric(days$Sub_metering_2), type = "l", ylab= "Energy sub metering", xlab="", col="red")
lines(DateTime,as.numeric(days$Sub_metering_3), type = "l", ylab= "Energy sub metering", xlab="",col="blue")
legend("topright",cex=0.6,lty="solid",legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black","red","blue"))
dev.off()
